version: '2'
services:
  servifind-app:
    image: servifind
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://servifind-postgresql:5432/ServiFind
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  servifind-postgresql:
    extends:
      file: postgresql.yml
      service: servifind-postgresql
